language: go

go_import_path: github.com/XenonLab-Studio/GoZork

go:
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"
  - master
  - tip

os:
  - linux
  - osx
  - windows

script:
  - go run *.go  # Start all the project files
  - go build # Build project
