os:
  - linux
  - osx
  - windows

sudo: false

language: go

go:
  - "1.6.x"
  - "1.7.x"
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"
  - master
  - tip

notifications:
    email: false

before_script:
  - go get github.com/XenonLab-Studio/GoZork

script:
  - env GO111MODULE=off go build
  - env GO111MODULE=on go test
